// <auto-generated />
namespace BootstrapSliderSnippet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ImageSlide : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ImageSlide));
        
        string IMigrationMetadata.Id
        {
            get { return "201708102009552_ImageSlide"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
